import { ConvexHttpClient } from "convex/browser";
import { readFileSync } from "node:fs";
import { api } from "../convex/_generated/api.js";
const c = new ConvexHttpClient(process.env.CONVEX_URL);
const SRC = "jn71dsyamvtgxvd1xan6ky032988bg5q";
const AVATAR = "/Users/armaanmanji/Downloads/Echos Content/male echos content/11-ugc-grooming.png";
const aurl = await c.mutation(api.sourceVideos.generateUploadUrl, {});
const { storageId } = await (await fetch(aurl, { method: "POST", headers: { "Content-Type": "image/png" }, body: readFileSync(AVATAR) })).json();
console.log("planning…");
const plan = await c.action(api.gemini.plan, { sourceVideoId: SRC, pipeline: "A", userPrompt: "Recreate this hair-care POV with the avatar as the subject. Clean.", modelIds: ["seedance-2.0-reference-to-video"], avatarStorageIds: [storageId] });
let p = await c.query(api.geminiPlans.get, { id: plan.planId });
console.log("\n=== changesFromPegasus (initial plan) ===");
console.log((p.fullPlan.changesFromPegasus ?? []).map((x, i) => `${i + 1}. ${x}`).join("\n") || "(none)");
console.log("\n--- prompt (first 280) ---\n" + p.fullPlan.models[0].calls[0].prompt.slice(0, 280));
console.log("\n>>> refining with feedback: mousse first, then cream <<<");
await c.action(api.gemini.refinePlan, { planId: plan.planId, feedback: "He actually applies the MOUSSE first, then the CREAM. Re-watch the video and make sure both products are applied in the correct order in the prompt." });
p = await c.query(api.geminiPlans.get, { id: plan.planId });
console.log("\n=== changesFromPegasus (after refine) ===");
console.log((p.fullPlan.changesFromPegasus ?? []).map((x, i) => `${i + 1}. ${x}`).join("\n") || "(none)");
console.log("\n--- prompt after refine (first 360) ---\n" + p.fullPlan.models[0].calls[0].prompt.slice(0, 360));
